service: myq-garage-closer
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: dist/app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
